volumes:
  cards-db-volume: {}

services:
  cards-db:
    image: bitnami/postgresql:17.0.0
    environment:
      POSTGRESQL_DATABASE: cards
      POSTGRESQL_USERNAME: dev
      POSTGRESQL_PASSWORD: dev
    volumes:
      - cards-db-volume:/bitnami/postgresql
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U dev' ]
      interval: 5s
      timeout: 5s
      retries: 3
