server:
  address: 0.0.0.0
  port: 8888

spring:
  application:
    name: embedded-backend

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.show_sql: true
    generate-ddl: true
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cards
    username: dev
    password: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/realms/devrealm/protocol/openid-connect/certs
